export const BULLET_LIBRARY = {
  "Software Engineer": [
    "Developed and maintained scalable RESTful APIs serving 500K+ daily requests with 99.9% uptime",
    "Reduced application load time by 40% through code optimization, caching strategies, and lazy loading",
    "Led migration of legacy monolith to microservices architecture, improving deployment frequency by 3x",
    "Implemented CI/CD pipelines using GitHub Actions, reducing release cycle from 2 weeks to 2 days",
    "Collaborated with cross-functional teams to deliver 15+ features on schedule across 4 quarters",
    "Authored technical documentation and onboarding guides used by 20+ engineers on the team",
    "Identified and resolved 50+ production bugs, reducing error rate by 35% within 3 months",
    "Designed and built real-time notification system handling 100K+ events per hour using WebSockets",
    "Mentored 3 junior engineers through code reviews, pair programming, and technical 1-on-1s",
    "Optimized database queries reducing average API response time from 800ms to under 120ms",
  ],
  "Frontend Developer": [
    "Built responsive React web applications used by 200K+ monthly active users",
    "Improved Core Web Vitals scores (LCP, FID, CLS) achieving 95+ Lighthouse performance score",
    "Migrated codebase from JavaScript to TypeScript, reducing runtime errors by 60%",
    "Implemented design system with 40+ reusable components adopted across 5 product teams",
    "Reduced bundle size by 45% through tree-shaking, code splitting, and asset optimization",
    "Integrated third-party APIs (Stripe, Twilio, Google Maps) with robust error handling and retry logic",
    "Developed accessible UI components meeting WCAG 2.1 AA standards for 1M+ users",
    "Collaborated closely with UX designers to translate Figma mockups into pixel-perfect interfaces",
    "Wrote unit and integration tests with Jest and React Testing Library, achieving 85% code coverage",
    "Led frontend guild of 8 engineers, standardizing code review processes and style guidelines",
  ],
  "Backend Developer": [
    "Designed RESTful and GraphQL APIs consumed by web and mobile clients with 99.95% availability",
    "Architected and deployed microservices on AWS (ECS, RDS, SQS) serving 10M+ requests per day",
    "Built real-time data pipelines processing 500GB of daily event data using Apache Kafka and Spark",
    "Implemented OAuth 2.0 / JWT authentication flow securing access for 300K+ registered users",
    "Reduced database query latency by 70% via indexing strategies and query plan analysis",
    "Deployed containerized Node.js / Python services with Docker and Kubernetes across 3 environments",
    "Automated infrastructure provisioning with Terraform, reducing environment setup time by 80%",
    "Designed caching layer with Redis, cutting database load by 50% during peak traffic periods",
    "Collaborated with security team to remediate 12 OWASP vulnerabilities in production APIs",
    "Built webhook delivery system with retry logic and dead-letter queues for 100% message delivery guarantee",
  ],
  "Product Manager": [
    "Defined product roadmap and prioritized backlog for a team of 12 engineers and 3 designers",
    "Launched 3 major product features resulting in 28% increase in user retention quarter-over-quarter",
    "Conducted 50+ user interviews and synthesized insights to identify and validate product-market fit",
    "Drove 0-to-1 launch of mobile app reaching 100K downloads in first 90 days post-launch",
    "Collaborated with Sales and Marketing to create go-to-market strategy that exceeded targets by 40%",
    "Defined and tracked OKRs across 4 teams, improving goal achievement rate from 60% to 85%",
    "Reduced average time-to-ship from 6 weeks to 2.5 weeks by implementing agile sprint ceremonies",
    "Built business case for $2M product investment, securing executive buy-in and budget approval",
    "Managed relationships with 5 enterprise clients during beta, incorporating feedback into 3 release cycles",
    "Analyzed A/B test results across 15 experiments to inform data-driven product decisions",
  ],
  "Data Scientist": [
    "Built and deployed machine learning models in production, improving prediction accuracy by 22%",
    "Designed recommendation engine using collaborative filtering, increasing click-through rate by 18%",
    "Processed and analyzed datasets of 50M+ rows using PySpark and Databricks",
    "Created interactive dashboards in Tableau and Power BI, used weekly by 30+ business stakeholders",
    "Reduced customer churn by 15% through predictive modeling and proactive outreach campaigns",
    "Developed NLP pipeline to classify 1M+ support tickets, automating routing and reducing handle time by 35%",
    "Conducted A/B testing framework design, enabling 20+ experiments simultaneously across product",
    "Collaborated with engineering to productionize Python models via FastAPI and MLflow",
    "Mentored 2 junior data analysts and established team coding standards and review workflows",
    "Presented findings to C-suite, translating complex models into actionable business recommendations",
  ],
  "Data Analyst": [
    "Analyzed user behavior data using SQL and Python to uncover insights improving conversion by 12%",
    "Built automated reporting pipelines eliminating 15 hours of manual work per week",
    "Created executive dashboards in Looker / Tableau tracking 20+ KPIs across business units",
    "Performed cohort analysis and funnel optimization leading to 8% improvement in trial-to-paid conversion",
    "Maintained and documented data warehouse schemas used by 50+ analysts and business partners",
    "Partnered with Marketing to measure campaign ROI, identifying $500K in underperforming spend",
    "Conducted statistical analysis on pricing experiments, informing a price strategy change worth $1.2M ARR",
    "Standardized metric definitions across 3 teams, eliminating conflicting data interpretations",
    "Trained non-technical stakeholders on self-service analytics tools, reducing ad-hoc report requests by 40%",
    "Identified data quality issues in ETL pipelines and worked with engineering to resolve root causes",
  ],
  "UX Designer": [
    "Led end-to-end UX design for mobile app with 500K+ users, from research through final QA",
    "Conducted usability studies with 30+ participants, identifying critical pain points in onboarding flow",
    "Redesigned checkout experience, reducing cart abandonment rate by 22%",
    "Built and maintained design system of 80+ components ensuring consistency across 6 product teams",
    "Facilitated design sprints with cross-functional stakeholders to align on product direction",
    "Created high-fidelity prototypes in Figma, reducing engineering rework by 30%",
    "Improved accessibility score from 62 to 91 by implementing WCAG 2.1 AA across core flows",
    "Partnered with data team to establish UX metrics (task completion, time-on-task) for design decisions",
    "Shipped 12 features across web and mobile in partnership with 3 engineering squads",
    "Mentored 2 junior designers through weekly critiques and structured feedback sessions",
  ],
  "Marketing Manager": [
    "Managed $1.5M annual digital marketing budget across paid search, social, and display channels",
    "Grew organic traffic by 180% YoY through SEO content strategy and technical site optimization",
    "Launched email nurture campaign achieving 42% open rate and 8% conversion rate (industry avg: 2.5%)",
    "Led brand refresh across all digital touchpoints, increasing brand recall score by 25% in surveys",
    "Built and managed Google Ads and Meta Ads campaigns generating 3.2x ROAS",
    "Developed influencer marketing program reaching 2M+ followers with 6.8% engagement rate",
    "Drove product launch that reached #1 on Product Hunt with 2,500+ upvotes in 24 hours",
    "Collaborated with 5 cross-functional teams to coordinate campaign messaging and launch timing",
    "Implemented marketing attribution model enabling better budget allocation across 8 channels",
    "Reduced CAC by 30% by optimizing landing pages, ad creative, and audience targeting",
  ],
  "Sales Representative": [
    "Exceeded quarterly sales quota by 127% for 6 consecutive quarters, ranking in top 5% of team",
    "Generated $2.3M in new business revenue through outbound prospecting and relationship building",
    "Managed a pipeline of 120+ active opportunities across SMB and mid-market segments",
    "Reduced average sales cycle from 45 days to 28 days by improving discovery and demo qualification",
    "Conducted product demonstrations for C-suite buyers at 40+ enterprise accounts",
    "Negotiated and closed 3 enterprise contracts totaling $800K in first 6 months of joining",
    "Built and maintained relationships with key accounts, achieving 95% renewal rate",
    "Collaborated with marketing to refine ICP and messaging, improving inbound lead quality by 40%",
    "Leveraged Salesforce CRM to track pipeline, forecast accurately, and prioritize activities",
    "Onboarded and mentored 4 new sales reps, sharing prospecting strategies and objection handling",
  ],
  "Project Manager": [
    "Delivered 8 cross-functional projects on time and within budget totaling $3.2M in value",
    "Led 15-member global team across 4 time zones using agile and waterfall methodologies",
    "Reduced project delivery time by 25% by identifying bottlenecks and restructuring team workflows",
    "Maintained detailed risk registers and mitigation plans, preventing 3 high-impact project failures",
    "Managed stakeholder communication across 6 business units via weekly status reports and reviews",
    "Implemented Jira and Confluence for project tracking, improving team visibility and velocity by 30%",
    "Coordinated vendor relationships across 5 third-party suppliers, ensuring SLA compliance",
    "Facilitated retrospectives and continuous improvement sessions, increasing sprint velocity by 20%",
    "Tracked $500K project budget with monthly variance reporting to executive leadership",
    "Championed PMO best practices adoption across 3 departments, standardizing delivery processes",
  ],
  "DevOps Engineer": [
    "Designed and implemented Kubernetes cluster managing 200+ microservices across 3 cloud regions",
    "Built CI/CD pipelines with Jenkins and GitLab CI reducing deployment time from 2 hours to 8 minutes",
    "Automated infrastructure provisioning with Terraform and Ansible across AWS, GCP, and Azure",
    "Reduced cloud infrastructure costs by 35% through right-sizing, reserved instances, and spot optimization",
    "Implemented centralized observability stack (Prometheus, Grafana, ELK) for 99.95% SLA monitoring",
    "Onboarded 8 development teams onto Kubernetes, providing training and runbook documentation",
    "Designed disaster recovery strategy achieving RTO of 15 minutes and RPO of 5 minutes",
    "Led on-call rotation and incident management, reducing MTTR from 45 minutes to under 12 minutes",
    "Migrated 40+ legacy services to containerized infrastructure with zero downtime deployments",
    "Implemented secret management with HashiCorp Vault, securing 200+ credentials across environments",
  ],
  "Customer Success Manager": [
    "Managed portfolio of 60 enterprise accounts with $8M in combined ARR, achieving 98% retention",
    "Drove NPS from 32 to 68 within 12 months through proactive outreach and issue resolution programs",
    "Identified upsell opportunities totaling $1.2M in expansion revenue across existing customer base",
    "Led quarterly business reviews with C-suite stakeholders at top 20 accounts",
    "Reduced time-to-value from 60 days to 21 days by overhauling customer onboarding program",
    "Built customer health score model enabling early churn detection with 85% accuracy",
    "Championed 3 customer feature requests from discovery to product roadmap inclusion",
    "Collaborated with Support, Product, and Sales teams to resolve escalations within 48 hours",
    "Produced and delivered 12 webinars and training sessions attended by 500+ users",
    "Created playbooks for renewals, expansions, and at-risk accounts adopted by entire CS team of 10",
  ],
  "Financial Analyst": [
    "Built 3-statement financial models supporting $50M acquisition decision and due diligence process",
    "Prepared monthly variance analysis and CFO-ready reporting packages for board presentations",
    "Automated financial reporting process using Excel VBA and Python, saving 20 hours per month",
    "Led annual budgeting process across 6 business units totaling $120M in operating expenses",
    "Identified $2.3M in cost savings opportunities through vendor consolidation and spend analysis",
    "Developed rolling 18-month cash flow forecast model with 95% accuracy rate",
    "Collaborated with operations team to build unit economics model for new market entry analysis",
    "Supported Series B fundraising by preparing investor data room and financial summaries",
    "Tracked and reported on 15 KPIs used by leadership for weekly business reviews",
    "Benchmarked company metrics against 8 public comparables for strategic planning initiatives",
  ],
  "HR Manager": [
    "Reduced time-to-hire from 52 days to 28 days by redesigning sourcing strategy and interview process",
    "Led full-cycle recruiting for 80+ roles across Engineering, Sales, and Operations in 12 months",
    "Designed and launched company-wide performance review process adopted by 500+ employees",
    "Reduced voluntary attrition by 18% through stay interviews, engagement surveys, and action planning",
    "Built onboarding program achieving 4.7/5.0 satisfaction rating from new hire surveys (n=200)",
    "Managed HRIS implementation (Workday) for 800-person organization, delivering on time and on budget",
    "Partnered with Legal to update employee handbook and ensure compliance across 3 state jurisdictions",
    "Launched DEI initiative resulting in 30% increase in underrepresented candidates in hiring pipelines",
    "Facilitated manager training programs on feedback, difficult conversations, and team building",
    "Administered annual compensation review cycle covering 600+ employees with $5M+ merit budget",
  ],
  "Graphic Designer": [
    "Designed brand identity systems for 15+ clients across SaaS, retail, and hospitality industries",
    "Created marketing collateral (ads, social, email) supporting campaigns that generated $3M+ in revenue",
    "Produced UI designs for web and mobile apps with 200K+ users in Figma and Sketch",
    "Led rebrand project for $10M ARR company, delivered across all digital and print touchpoints in 8 weeks",
    "Developed design system with 60+ components, reducing design-to-development handoff time by 40%",
    "Managed relationships with 3 print vendors, ensuring quality and on-time delivery for 40+ projects",
    "Collaborated with copywriters and marketing team to deliver 30+ campaign assets per quarter",
    "Increased social media engagement by 65% through redesigned visual content strategy",
    "Presented design concepts to stakeholders and iterated based on feedback within rapid timelines",
    "Trained 2 junior designers on brand standards, file naming conventions, and design workflows",
  ],
  "Teacher": [
    "Designed and delivered engaging curriculum for 28 students in Grades 6–8 covering Math and Science",
    "Improved average standardized test scores by 18 percentile points through targeted intervention strategies",
    "Differentiated instruction to support diverse learning needs including IEP and ELL students",
    "Integrated educational technology tools (Google Classroom, Kahoot, Nearpod) to increase engagement",
    "Built strong parent-teacher partnerships through monthly newsletters and bi-annual conferences",
    "Mentored 3 first-year teachers as part of school's new teacher induction program",
    "Led after-school STEM club for 20 students, culminating in regional science fair with 5 award winners",
    "Developed project-based learning units adopted by 4 other teachers in the department",
    "Maintained accurate records of student progress and communicated proactively with parents and administration",
    "Participated in professional development totaling 40+ hours annually in instructional best practices",
  ],
  "Nurse": [
    "Provided direct patient care for 8–12 patients per shift in fast-paced medical-surgical unit",
    "Administered medications, IV therapy, and treatments in accordance with physician orders and protocols",
    "Monitored and documented patient vitals, symptoms, and response to treatment every 4 hours",
    "Collaborated with interdisciplinary team including physicians, therapists, and social workers for comprehensive care plans",
    "Educated patients and families on discharge instructions, medication management, and follow-up care",
    "Mentored 5 new graduate nurses through 3-month preceptorship program with structured evaluations",
    "Responded to 10+ rapid response and code blue situations using ACLS protocols",
    "Maintained 100% compliance with infection control standards and hand hygiene protocols",
    "Participated in quality improvement initiative reducing CAUTI rates by 30% over 6 months",
    "Achieved charge nurse responsibilities including shift coordination and staff assignment for 20-bed unit",
  ],
  "Accountant": [
    "Prepared and filed federal and state tax returns for 80+ individual and business clients annually",
    "Managed month-end close process ensuring accuracy of $12M general ledger within 3 business days",
    "Reduced accounts receivable aging by 40% by implementing automated follow-up and collections workflow",
    "Supported external audit preparation by gathering and organizing documentation for 200+ audit requests",
    "Reconciled bank statements and intercompany accounts for 5 subsidiaries with zero material variances",
    "Implemented QuickBooks Online for 3 small business clients, improving reporting accuracy and timeliness",
    "Analyzed budget vs. actuals monthly, presenting findings and recommendations to leadership team",
    "Identified $180K in annual savings through vendor contract renegotiations and expense policy updates",
    "Maintained fixed asset register and calculated depreciation schedules across $2M in company assets",
    "Trained 2 accounting assistants on general ledger procedures, accounts payable, and expense reporting",
  ],
};

export const JOB_TITLE_LIST = Object.keys(BULLET_LIBRARY).sort();

export function getBulletsForTitle(jobTitle) {
  if (!jobTitle) return [];
  const exact = BULLET_LIBRARY[jobTitle];
  if (exact) return exact;
  // fuzzy match
  const lower = jobTitle.toLowerCase();
  const key = Object.keys(BULLET_LIBRARY).find(k => k.toLowerCase().includes(lower) || lower.includes(k.toLowerCase()));
  return key ? BULLET_LIBRARY[key] : [];
}
